### ISSUE TITLE
Teilschwärzung fehlerhaft

### ISSUE THREAD

**Issue by hauptmedia** [digitalservicebund/public_documents#1]
Hallo,

die Teilschwärzung in den PDF-Dokumenten ist erfolgt indem ein schwarzer Kasten drüber gemalt wurde. Dieser lässt sich z.B. mit dem Standard Programm "Vorschau" unter MacOS einfach wieder entfernen.

Viele Grüße

Julian Haupt

**Comment by chrkaatz** [comment]
Hallo Julian! Vielen Dank für dein Feedback.

Das ist mittlerweile nicht mehr vorhanden. Mittlerweile befinden sich unsere veröffentlichen Dokumente im [Transparenz Bereich](https://digitalservice.bund.de/transparenz) unserer Webseite.

Beste Grüße
Christian
